penjualan/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@getIndex');


//For Auth
Route::get('/login', 'Auth\AuthController@getLogin');
Route::post('/login', 'HomeController@postLogin');

Route::get('/register', 'HomeController@getRegisterPelanggan');
Route::post('/register', 'HomeController@registerPelanggan');

Route::get('/logout', 'HomeController@getLogout');

Route::get('/loginAdmin', 'AdminController@getLogin');
Route::post('/loginAdmin', 'AdminController@postLogin');
Route::get('/logoutAdmin', 'AdminController@getLogout');
Route::get('/firstLogin', 'AdminController@getFirstLogin');

Route::group(array('prefix'=>'/'), function(){
    Route::get('index', 'HomeController@getIndex');

    Route::get('category', 'HomeController@category');
    Route::get('category/{category}', 'HomeController@specificCategory');
    Route::get('detail/{id}', "HomeController@detailBarang");

    Route::get('cart', 'HomeController@getCart');
    Route::post('cart/add', 'HomeController@postAddCart');
    Route::post('cart/update', 'HomeController@postUpdateCart');
    Route::post('cart/delete', 'HomeController@postDeleteItemCart');

    Route::get('loginCashier', 'HomeController@getLoginCashier');
    Route::post('loginCashier', 'HomeController@postLoginCashier');
    Route::get('guest', 'HomeController@getGuest');
    Route::post('guest', 'HomeController@postGuest');

    Route::get('checkPesanan', 'HomeController@getCheckPesanan');
    Route::post('checkPesanan', 'HomeController@postCheckPesanan');

    Route::get('payment/step1', 'HomeController@getPayment1');
    Route::post('payment/step1', 'HomeController@postPayment1');

    Route::get('payment/step2', 'HomeController@getPayment2');
    Route::post('payment/step2', 'HomeController@postPayment2');

    Route::get('payment/step3', 'HomeController@getPayment3');
    Route::post('payment/step3', 'HomeController@postPayment3');
    Route::get('payment/success', 'HomeController@getPaymentSuccess');

    Route::get('order', 'HomeController@getOrders');
    Route::get('order/{id}', 'HomeController@getDetailOrder');
    Route::get('profil', 'HomeController@getProfil');
    Route::post('verifikasi', 'HomeController@postVerifikasi');

    Route::get('tagihan', 'HomeController@getTagihan');
    Route::get('tagihan/{id}', 'HomeController@getDetailTagihan');

    Route::get('settings', 'HomeController@getSettings');
    Route::post('settings', 'HomeController@postSettings');
    Route::post('settingPassword', 'HomeController@postSettingPassword');

    Route::post('/verifPesanan', 'HomeController@postVerifPesanan');
     
});

Route::group(array('prefix'=>'/administrator'), function(){
    Route::post('ubahStatusPesanan', 'AdminController@postUbahStatusPesanan');
    Route::get('detailPesanan/{id}', 'AdminController@getDetailPesanan');
    Route::get('cetakDetailPesanan/{id}', 'AdminController@getCetakDetailPesanan');
});

Route::post('/register-pelanggan', 'HomeController@registerPelanggan');

Route::group(array('middleware'=>'role:Pelanggan'),function(){
    Route::controller('pelanggan', 'PelangganController');
});

Route::group(array('middleware'=>'auth:admin'),function(){
    Route::controller('administrator','AdminController');
});

Route::get('/img/{filename}', function ($filename)
{
    $path = storage_path() . '/app/img/' . $filename;

    if(!File::exists($path)) return abort('400');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});
Route::get('/images/{filename}', function ($filename)
{
    $path = storage_path() . '/app/img/' . $filename;

    if(!File::exists($path)) return abort('400');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/imgProduct/{filename}', function ($filename)
{
    $path = storage_path() . '/app/produk/' . $filename;

    if(!File::exists($path)) return abort('400');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/imgUser/{filename}', function ($filename)
{
    $path = storage_path() . '/app/user/' . $filename;

    if(!File::exists($path)) return abort('404');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('/imgPembayaran/{filename}', function ($filename)
{
    $path = storage_path() . '/app/buktiPembayaran/' . $filename;

    if(!File::exists($path)) return abort('400');

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

penjualan/app/Pembayaran.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    protected $table = 'pembayaran';

    protected $fillable = array('pesanan_id', 'cicilan_perbulan', 'sisa_pembayaran', 'tanggal_jatuh_tempo', 'status_pembayaran');
    
    public $timestamps = false;

    public function detail_pembayaran(){
    	return $this->hasMany('App\Detail_Pembayaran', 'pembayaran_id');
    }

    public function getNotifAttribute(){
    	return $this->hasMany('App\Detail_Pembayaran', 'pembayaran_id')->where('verifikasi',0)->count();
    }

    public function pesanan(){
    	return $this->belongsTo('App\Pesanan', 'pesanan_id');
    }


}

penjualan/resources/views/admin/LogAdmin.blade.php
@extends('layouts.adminLayout')
@section('header')
  {{ Html::style('css/dataTables.bootstrap.css') }}
@stop
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Log Admin
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Customer Service</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class='row'>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class='box box-info'>
            <div class="box-header">
              <i class="fa fa-list"></i>
              <h3 class="box-title">Log Admin</h3>
            </div>
            <div class="box-body">
              <table class="table table-striped table-bordered dataTable">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Tanggal</th>
                    <th>Nama Customer Service</th>
                    <th>Email</th>
                    <th>Aktifitas</th>
                  </tr>
                </thead>
                <tbody>
                  <?php $c=1; ?>
                  @foreach($data as $d)
                  <tr>
                    <td>{{ $c++ }}</td>
                    <td>{{ $d->created_at }}</td>
                    <td>{{ $d->customer_service->nama }}</td>
                    <td>{{ $d->customer_service->email }}</td>
                    <td>{{ $d->aktivitas }}</td>
                  </tr>
                  <?php $c++; ?>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@stop
@section('js')
  <script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
<script>
  $(document).ready(function() {
    $('.dataTable').dataTable();
    
  });
</script>
@stop

penjualan/resources/views/admin/firstLogin2.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Batik Pramanca</title>

        <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{{ asset('/admin/bootstrap/css/bootstrap.min.css') }}">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                color: #FFFFF;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 72px;
                margin-bottom: 40px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                <div class="title"><strong>Akun Owner Sudah Aktif</strong></div>
                <a href="/loginAdmin" class="btn btn-sm btn-primary"><strong>Login</strong></a>
            </div>
        </div>
    </body>
</html>

penjualan/resources/views/admin/index.blade.php
@extends('layouts.adminLayout')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fa fa-cubes"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Barang</span>
              <span class="info-box-number">{{$data['barang']}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fa fa-opencart"></i></span>

            <div class="info-box-content">
              <span class='info-box-text'>Total Pesanan</span>
              <span class="info-box-number">{{$data['pesanan']}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->

        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>

        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-money"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Penerimaan</span>
              @if(is_null($data['penerimaan']->total))
              <span class="info-box-number">Rp. 0</span>
              @else
              <span class="info-box-number">Rp. {{ number_format($data['penerimaan']->total,0 , ',' , '.')}}</span>
              @endif
              <span class="info-box-text">Piutang</span>
              @if(is_null($data['total_piutang']->total))
              <span class="info-box-number">Rp. 0</span>
              @else
              <span class="info-box-number">Rp. {{ number_format($data['total_piutang']->total, 0 , ',' , '.')}}</span>
              @endif
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fa fa-users"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Customer</span>
              <span class="info-box-number">{{$data['customer']}}</span>
              <span class="info-box-text">Adminstrator</span>
              <span class="info-box-number">{{$data['customer']}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

      
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection

penjualan/resources/views/admin/laporan.blade.php
@extends('layouts.adminLayout')

@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Laporan
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator"><i class="fa fa-dashboard"></i> Beranda</a></li>
        <li class="active">Laporan</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class='row'>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="box box-warning">
            <div class="box-header">
            <i class="fa fa-list"></i>
              <h3 class="box-title">Laporan</h3>
            </div>
            <div class="box-body">
              <div class="row">
              <form action="/administrator/laporan" method="POST">
                  <div class="form-group col-md-12">
                    <label for="nmprdk" class="col-sm-3 control-label">Jenis Laporan</label>
                    <div class="col-sm-9">
                      <select class="validate[required] form-control" name="jenis" id="jenis">
                        <option value="">-- Pilih Jenis Laporan --</option>
                        <option value="penjualan_semua">Penjualan Semua</option>
                        <option value="penjualan_tunai">Penjualan Tunai</option>
                        <option value="penjualan_kredit">Penjualan Kredit</option>
                        <option value="beban">Beban</option>
                        <option value="penerimaan">Penerimaan</option>
                        <option value="piutang">Piutang</option>
                        <option value="persediaan">Persediaan</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group col-md-12">
                    <label for="nmprdk" class="col-sm-3 control-label">Jenis Penjualan</label>
                    <div class="col-sm-9">
                      <select class="validate[required] form-control" name="penjualan" id="penjualan" disabled="false">
                        <option value="">-- Pilih Jenis Penjualan --</option>
                        <option value="semua">Semua</option>
                        <option value="offline">Offline</option>
                        <option value="online">Online</option>
                      </select>
                    </div>
                  </div>
                  <div class="form-group col-md-12">
                    <label for="nmprdk" class="col-sm-3 control-label">Tahun</label>
                    <div class="col-sm-9">
                      <input type="text" class="validate[required] form-control" name="tahun" id="tahun" disabled="false">
                    </div>
                  </div>
                  <div class="form-group col-md-12">
                    <label for="nmprdk" class="col-sm-3 control-label">Bulan</label>
                    <div class="col-sm-9">
                      <select class="validate[required] form-control" name="bulan" id="bulan" disabled="false">
                        <option value="">-- Pilih Bulan --</option>
                        <option value="01">Januari</option>
                        <option value="02">Februari</option>
                        <option value="03">Maret</option>
                        <option value="04">April</option>
                        <option value="05">Mei</option>
                        <option value="06">Juni</option>
                        <option value="07">Juli</option>
                        <option value="08">Agustus</option>
                        <option value="09">September</option>
                        <option value="10">Oktober</option>
                        <option value="11">November</option>
                        <option value="12">Desember</option>
                      </select>
                    </div>
                  </div>
                  <div class="col-md-5">
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                  </div>
              </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @endsection
  @section('js')
    <script type="text/javascript">
      $('#jenis').on('change', function() {
          var jenis = this.value;

          switch(jenis){
            case 'penjualan_semua':
              $('#penjualan').removeAttr('disabled');
              $('#tahun').removeAttr('disabled');
              $('#bulan').removeAttr('disabled');
              break;
            case 'penjualan_kredit':
              $('#penjualan').removeAttr('disabled');
              $('#tahun').removeAttr('disabled');
              $('#bulan').removeAttr('disabled');
              break;
            case 'penjualan_tunai':
              $('#penjualan').removeAttr('disabled');
              $('#tahun').removeAttr('disabled');
              $('#bulan').removeAttr('disabled');
              break;
            case 'beban':
              $('#penjualan').attr('disabled', true);
              $('#tahun').removeAttr('disabled');
              $('#bulan').removeAttr('disabled');
              break;
            case 'penerimaan':
              $('#penjualan').removeAttr('disabled');
              $('#tahun').removeAttr('disabled');
              $('#bulan').removeAttr('disabled');
              break;
            case 'piutang':
              $('#penjualan').attr('disabled', true);
              $('#tahun').attr('disabled', true);
              $('#bulan').attr('disabled', true);
              break;
            case 'persediaan':
              $('#penjualan').attr('disabled', true);
              $('#tahun').removeAttr('disabled');
              $('#bulan').removeAttr('disabled');
              break;
          }
      });
    </script>
  @endsection

penjualan/resources/views/admin/laporanBarang.blade.php
@extends('layouts.adminLayout')
@section('header')
  {{ Html::style('css/dataTables.bootstrap.css') }}
@stop
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Laporan
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Laporan Barang</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->

      <div class='row'>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class='box box-info'>
            <div class="box-header">
              <i class="fa fa-list"></i>
              <h3 class="box-title">{{$judul}}</h3>
              <hr>
              <form action="/administrator/laporan-download" method="POST">
                <input  type="hidden" value="{{$form['jenis']}}" name="jenis">
                <input  type="hidden" value="{{$form['penjualan']}}" name="penjualan">
                <input  type="hidden" value="{{$form['tahun']}}" name="tahun">
                <input  type="hidden" value="{{$form['bulan']}}" name="bulan">
                <a href="/administrator/laporan-barang" class="btn btn-warning btn-sm pull-left">Update Barang Bulan ini</a>
                <button type='submit' class="btn btn-sm btn-info pull-right">Download Laporan</i></button>
              </form>
            </div>
            <div class="box-body">
              <table class="table table-striped table-bordered dataTable">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Kode Barang</th>
                    <th>Nama Barang</th>
                    <th>Harga Pokok</th>
                    <th>Harga</th>
                    <th>Harga Grosir</th>
                    <th>Stok</th>
                    <th>Kategori</th>
                    <th>Last Update</th>
                  </tr>
                </thead>
                <tbody>
                  <?php $c=1; ?>
                  @foreach($data as $d)
                  <tr>
                    <td>{{ $c }}</td>
                    <td>{{ $d->Kode_Barang}}</td>
                    <td>{{ $d->Nama_Barang }}</td>
                    <td>Rp {{ number_format($d->Harga_Pokok, 0, ',','.') }}</td>
                    <td>Rp {{ number_format($d->Harga, 0, ',','.') }}</td>
                    <td>Rp {{ number_format($d->Harga_Grosir, 0, ',','.') }}</td>
                    <td>{{ $d->Stok }}</td>
                    <td>{{ $d->Kategori }}</td>
                    <td>{{ $d->Last_Update }}</td>
                  </tr>
                  <?php $c++; ?>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@stop
@section('js')


  <script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
  <script>
    $('.detail-barang').click(function() {
      $('#detail_nama').val($(this).data('nama'));
      $('#detail_harga').val($(this).data('harga'));
      $('#detail_stok').val($(this).data('stok'));
      $('#detail_id').val($(this).data('id'));
      $('#detail_keterangan').val($(this).data('keterangan'));
      $('#detailBarang').modal('show');
    });
    $('.detail-stok').click(function() {
      $('#stok_data').val($(this).data('stok'));
      $('#stok_id').val($(this).data('id'));
    });
    $('#tambah-kategori').click(function() {
      $('#tambah_kategori_nama').val("");
    });
    $('.edit-kategori').click(function() {
      $('#edit_kategori_nama').val($(this).data('nama'));
      $('#edit_kategori_id').val($(this).data('id'));
    });
  </script>
<script>
</script>
@stop

penjualan/resources/views/admin/login.blade.php
@extends('layouts.header')
@section('style')
	
@stop
@section('content')
<div id="content">
    <div class="container">

        <div class="col-md-12">

            <ul class="breadcrumb">
                <li><a href="/index">Home</a>
                </li>
                <li>Log in</li>
            </ul>

        </div>

        <div class="col-md-6 col-md-offset-3">
            <div class="box">
                <h3>Login Administrator</h3>
                <form action="/loginAdmin" method="post" data-toggle='validator'>
                    @if(Session::has('loginFailed'))
                    <div class="alert alert-danger alert-dismissable" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Login Gagal!</strong> Email atau password salah.
                    </div>
                    @endif
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" required data-error='Email tidak valid'>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                    </div>
                </form>
            </div>
        </div>


    </div>
    <!-- /.container -->
</div>
<!-- /#content -->
@stop
@section('js')
<script src="{{ asset('/js/bootbox.min.js') }}"></script>
<script src="{{ asset('/js/toastr.min.js') }}"></script>
<script src="{{ asset('/js/validator.js') }}"></script>
@stop

penjualan/resources/views/admin/pesanan.blade.php
@extends('layouts.adminLayout')
@section('header')
  {{ Html::style('/css/dataTables.bootstrap.css') }}
  {{ Html::style('/css/bootstrap-editable.css') }}
  <style type="text/css">
    .badge-notify{
       background:red;
       position:absolute;
       top: -10px;
       left: 20px;
    }
  </style>
@stop
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Pesanan
      </h1>
      <ol class="breadcrumb">
        <li><a href="/administrator"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Pesanan</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class='row'>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class='box box-info'>
            <div class="box-header">
              <i class="fa fa-list"></i>
              <h3 class="box-title">Daftar Pesanan</h3>
            </div>
            <div class="box-body">
              <table class="table table-striped table-bordered table-condensed" id='dataTable'>
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Tanggal</th>
                    <th>Kode Pesanan</th>
                    <th>Jenis Transaksi</th>
                    <th>Nama Pelanggan</th>
                    <th>Total Pembayaran</th>
                    <th>Status</th>
                    <th>Operasi</th>
                  </tr>
                </thead>
                <tbody>
                  <?php $c=1; ?>
                  @foreach($data as $d)
                  <tr>
                    <td>{{ $c++ }}</td>
                    <td>{{ $d->tanggal_pesanan }}</td>
                    <td>{{ $d->kode_pesanan }}</td>
                    <td>{{ $d->jenis_transaksi }}</td>
                    <td>{{ $d->nama_pelanggan }}</td>
                    <td>Rp {{ number_format($d->total_pembayaran, 0, ',','.') }}</td>
                    <td>
                    @if($d->verifikasi == 'Konfirmasi Pembayaran')
                          <strong style='color:#303F9F;'>Konfirmasi Pembayaran</strong>
                    @elseif($d->verifikasi == 'Dalam Pengiriman')
                          <strong style='color:#303F9F;'>Dalam Pengiriman</strong>
                    @elseif($d->verifikasi == 'Lunas Uang Muka')
                          <strong style='color:#303F9F;'>Lunas Uang Muka</strong>
                    @else
                          <strong style='color:#009688;'>Diterima</strong>
                    @endif
                    </td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-xs btn-primary" href="/administrator/detailPesanan/{{ $d->id }}"><i class="fa fa-eye"></i></a>
                      </div>
                      <div class="btn-group">
                        <a class="btn btn-xs btn-success" href="/administrator/verifikasi-pembayaran/{{ $d->id }}"><i class="fa fa-edit"></i></a>
                        @if($d->pembayaran->notif > 0)
                          <span class="badge badge-xs badge-notify" style="z-index:99;">{{$d->pembayaran->notif}}</span>
                        @endif
                      </div>
                      <div class="btn-group">
                        <a class="delete btn btn-xs btn-danger" data-rowid="{{$d->id}}" data-kode="{{$d->kode_pesanan}}"><i class="fa fa-times"></i></a>
                      </div>
                   </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@stop
@section('js')
<script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
<script src="{{ asset('/js/bootstrap-editable.min.js') }}"></script>
<script>
  $(document).ready(function() {

    $('#dataTable').dataTable({
      "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
        $('.edit').editable();
      }
    });
  });

  $('.delete').click(function() {
      var rowid = $(this).data('rowid');
      var kodePesanan = $(this).data('kode');

      bootbox.confirm("Hapus Pesanan <strong>"+kodePesanan+" </strong> ini?", function(result) {
        if (result) {
          toastr.options.timeOut = 0;
          toastr.options.extendedTimeOut = 0;
          toastr.info('<i class="fa fa-spinner fa-spin"></i><br>Sedang menghapus...');
          toastr.options.timeOut = 5000;
          toastr.options.extendedTimeOut = 1000;
          $.post("/administrator/delete-pesanan", {rowid: rowid})
          .done(function(result) {
            window.location.replace("/administrator/pesanan/");
          })
          .fail(function(result) {
            toastr.clear();
            toastr.error('Kesalahan server! Silahkan reload halaman dan coba lagi');
          });
        };
      }); 
    });
</script>
@stop